### ISSUE TITLE
storageClass is useless

### ISSUE THREAD

**Issue by kunthar** [dojot/ansible-dojot#192]
* **I'm submitting a ...**
  * [x ] bug report

* **Do you want to request a *feature* or report a *bug*?**
Reporting a bug 

* **What is the current behavior?**
ansible-dojot/inventories/x/group_vars/all/volumes.yaml
dojot_storage_class_name: "dojot-ceph-block"
is not overloaded in installation time. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
create rook operator
create rook storage class. 
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: dojot-ceph-block
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    # clusterID is the namespace where the rook cluster is running
    clusterID: rook-ceph
    # Ceph pool into which the RBD image shall be created
    pool: replicapool

    # (optional) mapOptions is a comma-separated list of map options.
    # For krbd options refer
    # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
    # For nbd options refer
    # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
    # mapOptions: lock_on_read,queue_depth=1024

    # (optional) unmapOptions is a comma-separated list of unmap options.
    # For krbd options refer
    # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
    # For nbd options refer
    # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
    # unmapOptions: force

    # RBD image format. Defaults to "2".
    imageFormat: "2"

    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: layering

    # The secrets contain Ceph admin credentials.
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

    # Specify the filesystem type of the volume. If not specified, csi-provisioner
    # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
    # in hyperconverged settings where the volume is mounted on the same node as the osds.
    csi.storage.k8s.io/fstype: ext4

# Delete the rbd volume when a PVC is deleted
reclaimPolicy: Retain

# Optional, if you want to add dynamic resize for PVC.
# For now only ext3, ext4, xfs resize support provided, like in Kubernetes itself.
allowVolumeExpansion: true
```
- Run playbooks in order.

``` ansible-playbook --private-key=~/.ssh/id_rsa --become --user=root --become-user=root  -i inventories/x  volume.yaml ```
```
PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************
master_host                : ok=0    changed=0    unreachable=0    failed=0    skipped=24   rescued=0    ignored=0
worker_host                : ok=1    changed=0    unreachable=0    failed=0    skipped=24   rescued=0    ignored=0

Sunday 12 June 2022  22:41:14 +0300 (0:00:00.047)       0:00:04.790 ***********
===============================================================================
Gathering Facts ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.22s
volumes/zookeeper : Create zookeeper volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.09s
volumes/x509-identity-mgmt : Create x509_identity_mgmt volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.07s
volumes/certificate-acl : Create Certificate ACL volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.06s
volumes/zookeeper : Create zookeeper volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.05s
volumes/certificate-acl : Create Certificate ACL volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.05s
volumes/kafka : Create kafka volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
volumes/kong : Create kong volume ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/kafka-ws : Create kafka_ws volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/postgres : Create postgres volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/prometheus : Create prometheus volume ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/influxdb : Create influxdb volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/mongodb : Create mongodb volume ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/minio : Create minio volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/x509-ejbca : Create ejbca volume --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/prometheus : Create prometheus volume ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/x509-identity-mgmt : Create x509_identity_mgmt volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.04s
volumes/minio : Create minio volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/mongodb : Create mongodb volume ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
volumes/kafka : Create kafka volume -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
```

- Result is totally wrong. Actually there is no volume created.

``` kubectl get pv ```
No resources found

* **What is the expected behavior?**
Volumes should be added ON ceph storageclass.

* **Please tell us about your environment:**

$ ``` kubectl version ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
  
dojot_version: v0.7.1

``` ansible --version ```
ansible [core 2.12.6]
  config file = /Users/kunthar/work/bulutbroker/clients/vestel/k8s/ansible-dojot/ansible.cfg
  configured module search path = ['/Users/kunthar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kunthar/work/bulutbroker/clients/vestel/k8s/ansible-dojot/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/kunthar/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/kunthar/work/bulutbroker/clients/vestel/k8s/ansible-dojot/venv/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
